FROM ubuntu:latest

# Create app directory
WORKDIR /usr/src/app

RUN apt-get update

RUN apt-get install -y git-core curl build-essential openssl libssl-dev \
 && git clone https://github.com/nodejs/node.git \
 && cd node \
 && ./configure \
 && make \
 && sudo make install

 RUN npm install